config/routes.rb
Read::Engine.routes.draw do
  resources :articles
  #get "profil/:id" => "profile#show"
  #get "profil/:id" => "profile#show"
  match "profil/*id" => "profile#show", :as => "profile", :format => "html"

  root :to => "home#index"
  match "*id" => "home#show", :as => "read"

end

app/models/read/article.rb
# -*- coding: utf-8 -*-
require 'bluecloth'
require 'digest/md5'
require 'uuidtools'
require 'typedown'
require 'cgi'


module Read
  class Article < ActiveRecord::Base
    set_primary_key :token

    attr_accessible :body, :email, :leadin, :path, :title, :token
    attr_accessor :seed

    before_save :calc_profile_hash

    def profile
      @profile ||= Gravatar.find_by_nick(self.profile_hash)
    end

    def byline
      self.profile.display_name
    rescue
      nil
    end


    def byline_bio
      self.profile.about_me
    rescue
      ""
    end


    def static_page?
      false
    end


    def calc_profile_hash
      self.profile_hash = Gravatar.lookup_hash email.downcase
      self
    end


    def reset_token
      self.token = random
      self
    end


    def reset_path
      t = self.title && self.title.tr("æøåÆØÅ", "eoaEOA").gsub(/[^0-9A-Za-z\ \-]/, '').gsub(" ", "-").downcase || ""
      self.path = Time.now.strftime("%Y/%W/#{t}/#{random[0..5]}")
      self
    end


    def leadin_as_html
      Typedown::Document.new(self.leadin).to_html.html_safe
    end


    def body_as_html
      Typedown::Document.new(self.body).to_html.html_safe
    end


    def words
      s = ""
      s << leadin.dup if leadin
      s << " "
      s << body.dup if body 
      s.gsub!(/\w+/, 'X')
      s.gsub!(/[^X]/, '')
      s.length
    end


    def typedown= v
      doc = Typedown::Section.sectionize(v)
      self.title = doc.title
    
      found = false
      self.leadin = ""
      self.body = ""
      doc.body.to_s.strip.lines.each do |line|
        unless found
          if line.strip.length == 0
            found = true
            next
          end
          self.leadin << line.strip
          self.leadin << " "
        else
          self.body << line
        end
      end
      self.leadin.strip!
      self.leadin.gsub!('//.', '')
      self.body.gsub!(/^(!+ )/, '!\0')
      self.body.strip!
    end


    private
    def random
      # Allow seed for predictable path generation on create + delete + create
      random = if(seed)
                 Digest::SHA1.digest(seed + ".fdasFDAhfs4332daafdsFaa_SaLT,")
               else
                 UUIDTools::UUID.random_create.raw
               end

      random = Base32::Crockford.encode(random).downcase
      random
    end

  end
end

app/models/read/cloudmailin.rb
require 'iconv'
require 'mail'
require 'digest/sha1'

class Cloudmailin
  def self.default_from
    ENV['default_from'] || "from@example.com"
  end


  def self.secret mail_from
    digest = Digest::SHA1.digest(mail_from + ".fdasFDAhfs433fdasFaa_SaLT," + default_from)
    token = Base32::Crockford.encode(digest).downcase[0..6]
    token
  end


  def self.secret_mail mail_from
    s = self.secret mail_from, default_from
    Cloudmailin:default_from.gsub("@", "+#{s}@")
  end


  def self.validate mail_from, mail_to
    s = self.secret(mail_from)
    t = mail_to.split('@')[0].split('+')[-1].strip
    (s || "x").downcase === (t || "y").downcase
  end


  def self.email m
    m.split("<")[-1].split(">")[0].strip
  end


  def validate
    f = Cloudmailin.email(self.from)
    t = Cloudmailin.email(self.to[0])
    f && t && Cloudmailin.validate(f, t) || false
  end


  def secret
    f = Cloudmailin.email(from)
    Cloudmailin.secret(f)
  end


  def secret_mail
    f = Cloudmailin.email(from)
    Cloudmailin.secret_mail(f)
  end


  def initialize message
    @mail = Mail.new(message)
  end


  def to 
    (@mail && @mail.to) || nil
  end


  def from
    (@mail && @mail[:from].decoded) || nil
  end


  def subject
    s = (@mail && @mail.subject) || nil
    if s && s.respond_to?(:encode)
      s.encode("utf-8")
    else
      s
    end
  end


  def text_body
    if(@mail &&  @mail.text_part && @mail.text_part.body)
      m = @mail.text_part.body.decoded
      charset = @mail.text_part.charset
      text = charset ? Iconv.conv("utf-8", charset, m) : m
      (text.respond_to? :force_encoding) ? text.force_encoding("utf-8") : text
    elsif(@mail && @mail.body && @mail.content_type.to_s.include?("text/plain"))
      m = @mail.body.decoded
      charset = @mail.charset
      text = charset ? Iconv.conv("utf-8", charset, m) : m
      (text.respond_to? :force_encoding) ? text.force_encoding("utf-8") : text
    else
      nil
    end
  end
end

app/models/read/gravatar.rb
# -*- coding: utf-8 -*-
require 'restclient'
require 'digest/md5'
require 'json'

module Read
  class Gravatar
    class GravatarException < StandardError; end

    def self.find_by_email email
      self.new(email)
    end

    def self.find_by_nick nick
      self.new(nick)
    end

    def self.find_by_hash h
      self.new(h)
    end

    def self.lookup_hash email
      digest = Digest::MD5.hexdigest(email)
      @gravatar_hash = digest # email hash
    end


    def nick
      preferred_username
    end

    def bio
      about_me
    end



    def initialize email
      if email.include? '@'
        digest = Digest::MD5.hexdigest(email)
        @gravatar_hash = digest # email hash
      else
        @gravatar_profile ||= get_gravatar_profile(email) # nick or hash
        @gravatar_hash = served_hash
      end
    end


    def gravatar_profile
      @gravatar_profile ||= get_gravatar_profile(@gravatar_hash)
    end


    def thumbnail_url
      "http://gravatar.com/avatar/#{@gravatar_hash}.png?d=monsterid"
    end


    def photo_url size
      "http://gravatar.com/avatar/#{@gravatar_hash}.png?size=#{size}"
    end

    def preferred_username
      gravatar_profile && gravatar_profile['preferredUsername']
    end


    def about_me
      gravatar_profile && gravatar_profile['aboutMe']
    end


    def name
      gravatar_profile && gravatar_profile['name']['formatted']
    end


    def served_hash
      gravatar_profile && gravatar_profile['hash']
    end


    def display_name
      gravatar_profile && gravatar_profile['displayName']
    end


    private
    def get_gravatar_profile gravatar_hash
      url = "http://nb.gravatar.com/#{gravatar_hash}.json"
      res = RestClient.get(url)

      case res.code
      when 200 # Net::HTTPOK
        json = JSON.parse(res.body)
        json && json['entry'] && json['entry'][0] || nil
      when 404 #Net::HTTPNotFound
        nil
      else
        raise res.inspect
        raise GravatarException.new("Could not fetch profile from gravatar.com")
      end
    end
  end
end

app/controllers/read/application_controller.rb
module Read
  class ApplicationController < ActionController::Base
  end
end

app/controllers/read/articles_controller.rb
require_dependency "read/application_controller"

module Read
  class ArticlesController < ApplicationController
    skip_before_filter :verify_authenticity_token
    before_filter :authenticate, :only => [ :index, :create, :new ]


    # GET /articles
    # GET /articles.json
    def index
      @articles = Article.order('created_at DESC').paginate(:page => @page, :per_page => 10)
      @javascript = true
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @articles }
      end
    end

    # GET /articles/1
    # GET /articles/1.json
    def show
      @article = Article.find(params[:id])
      @javascript = true
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @article }
      end
    end

    # GET /articles/new
    # GET /articles/new.json
    def new
      @article = Article.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @article }
      end
    end
  
    # GET /articles/1/edit
    def edit
      @article = Article.find(params[:id])
    end
  
    # POST /articles
    # POST /articles.json
    def create
      @article = Article.new(params[:article])
      @article.reset_token
      @article.reset_path
  
      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, notice: 'Innlegget ble opprettet.' }
          format.json { render json: @article, status: :created, location: @article }
        else
          format.html { render action: "new" }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /articles/1
    # PUT /articles/1.json
    def update
      @article = Article.find(params[:id])
  
      respond_to do |format|
        if @article.update_attributes(params[:article])
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /articles/1
    # DELETE /articles/1.json
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
  
      respond_to do |format|
        format.html { redirect_to articles_url }
        format.json { head :no_content }
      end
    end


private
    def authenticate
      user_id, password = ENV['ADMIN_USER'] || "admin", ENV['ADMIN_PASSWORD'] || "kueR10"
      authenticate_or_request_with_http_basic do |id, password| 
        id == user_id && password == password
      end
    end

  end
end

app/controllers/read/cloudmailin_controller.rb
require 'mail'
require 'digest/md5'
require 'base32_pure'


module Read
  class CloudmailinController < ApplicationController
    skip_before_filter :verify_authenticity_token


    def index
      render :text => 'ok', :status => 200
    end


    def create
      cm = Cloudmailin.new params[:message]

      mfrom = cm.from
      msubject = cm.subject
      mto = cm.to[0]
      Rails.logger.log Logger::INFO, mfrom
      Rails.logger.log Logger::INFO, msubject
      #Rails.logger.log Logger::INFO, params[:plain]

      unless cm.validate
        if mto.include? Cloudmailin:default_from
          UserMailer.welcome(mfrom, cm.secret_mail).deliver
          render :text => 'success', :status => 200
        else
          render :text => 'non-matching email address', :status => 404 # :unprocessable_entity
        end
        return
      end

      mbody = cm.text_body || params[:plain] || ""
      mbody.strip!


      # Make sure subject doesn't start with '! '
      msubject.gsub!(/^\!\ /, '')
      typedown = ""
      # Add subject as title unless title already exists in body
      typedown << ("! " + msubject + "\n\n") unless(mbody[0..1] === '! ')

      # Add body
      typedown << mbody

      @article = Article.new

      # Content fields
      @article.typedown = typedown
      @article.email = mfrom.split("<")[-1].split(">")[0].strip

      # Autofields
      @article.reset_token
      @article.reset_path

      if @article.save
        UserMailer.article(@article).deliver
        render :text => 'success', :status => 200 # a status of 404 would reject the mail
      else
        render :xml => @article.errors, :status => 404 # :unprocessable_entity
      end
    end
  end
end

app/controllers/read/home_controller.rb
require_dependency "read/application_controller"

module Read
  class HomeController < ApplicationController
    # GET /articles
    # GET /articles.json
    def index
      @articles = Article.order('created_at DESC').paginate(:page => @page, :per_page => 10)
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @articles }
      end
    end

    def show
      @article = Article.find_by_path(params[:id])
      respond_to do |format|
        format.html {
          if @article
            response.headers['Cache-Control'] = 'public, max-age=15'
            render :show
          else
            redirect_to("/")
          end
        } # show.html.erb
      end
    end

  end
end

app/controllers/read/profile_controller.rb
require_dependency "read/application_controller"

module Read
  class ProfileController < ApplicationController
    def show
      email = params[:id];
      @byline = Gravatar.find_by_nick(email)
      @articles = Article.where(:profile_hash => @byline.served_hash).order('created_at DESC').paginate(:page => @page, :per_page => 10)
      @thumbnail = @byline.thumbnail_url
      @email
      
      response.headers['Cache-Control'] = 'public, max-age=15'
      render
    end
  end
end

app/helpers/read/application_helper.rb
module Read
  module ApplicationHelper
  end
end

app/helpers/read/articles_helper.rb
module Read
  module ArticlesHelper
  end
end

app/helpers/read/home_helper.rb
module Read
  module HomeHelper
  end
end

app/helpers/read/profile_helper.rb
module Read
  module ProfileHelper
  end
end

app/views/read/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = '<%= @disqus %>';
    var disqus_identifier = '<%= @article.path %>';
    var disqus_url = 'http://<%= request.host %>/<%= @article.path %>';
    var disqus_developer = 0;

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Skru på javascript for å se <a href="http://disqus.com/?ref_noscript">kommentarer</a>.</noscript>

app/views/read/articles/_form.html.erb
<style>
  .wide {
    width: 98%;
  }
</style>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Tittel' %><br />
    <%= f.text_field :title, :class => 'wide' %>
  </div>
  <div class="field">
    <%= f.label :email, 'Epost' %><br />
    <%= f.text_field :email, :class => 'wide' %>
  </div>
  <div class="field">
    <%= f.label :leadin, 'Ingress' %><br />
    <%= f.text_area :leadin, :rows => 2, :class => 'wide' %>
  </div>
  <div class="field">
    <%= f.label :body, 'Brødtekst' %><br />
    <%= f.text_area :body, :rows => 10, :class => 'wide' %>
  </div>
  <div class="actions">
    <%= f.submit 'Lagre' %>
  </div>
<% end %>

app/views/read/articles/_read.html.erb
<h1 class="title"><%= @article.title %></h1>

<div class="leadin"><%= @article.leadin_as_html %></div>

<% unless(@article.static_page?) %>
<p class="byline">
  <% if(@article.byline) %>
    <i><%= link_to @article.byline, profile_url(@article.profile.nick) if @article.byline %></i> |
  <% end %>
  <%= @article.words %> ord | 
  <%= @article.created_at.to_date %>
</p>
<% end %>


<div class="body">
  <%= @article.body_as_html %>
</div>
<hr />
<div class="footer">
  <b><%= link_to @article.byline, profile_url(@article.profile.nick) if @article.byline %></b> |
  <%= @article.byline_bio %>
</div>

<% unless(@article.static_page?) %>
<p class="source">Kilde: <%=
     host, port = request.env['HTTP_HOST'], request.env['SERVER_PORT']
     host.gsub!("www.", "")
     path = read_url(@article.path)
     @source = path
     link_to path, path
  %>
</p>
<% end %>

app/views/read/articles/_twitter_card.html.erb
  <meta name="twitter:card" content="summary">
  <meta name="twitter:url" content="http://ordskifte.net/<%= @article && @article.path %>">
  <meta name="twitter:title" content="<%= @article && @article.title.html_safe || 'ordskifte.net' %>">
  <meta name="twitter:description" content="<%= @article && @article.leadin.html_safe || 'Ordskifter og andre vendinger' %>">

app/views/read/articles/edit.html.erb
<div class="menu">
  <ul>
    <li><%= link_to 'Avbryt', @article, :class => 'menu' %></li>
  </ul>
</div>

<h1>Rediger innlegg</h1>

<%= render 'form' %>

app/views/read/articles/index.html.erb
<div class="article">

<% @articles.each do |article| %>
  <div class="entry">
    <% path = article_path(article) %>
    <h3><%= article.title %></h3>  
    <p class="byline">
    </p>
    <p class="byline">
      <i><%= article.byline %></i>
      | <%= article.created_at.to_date %>
      | <%= path %>
    </p>
    <% 
       leadin = article.leadin
       leadin = (leadin[0..140] + "...") unless(leadin.length <= 143)
    %>
    <p><%= leadin %></p>
    <p><%= link_to "Rediger", article %></p>
  </div>
<% end %>
<p><%= 
      WillPaginate::ViewHelpers.pagination_options[:prev_label] = "&laquo; Yngre".html_safe
      WillPaginate::ViewHelpers.pagination_options[:next_label] = "Eldre &raquo;".html_safe
      will_paginate @articles 
      %></p>


<p><%= link_to 'Nytt innlegg', new_article_path %></p>

</div>

app/views/read/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/read/articles/show.html.erb
<div class="menu">
  <ul>
    <li><%= link_to 'Endre', edit_article_path(@article), :class => 'menu' %></li>
    <li><%= link_to 'Slett', @article, :confirm => 'Er du sikker?', :method => :delete, :class => 'menu' %></li>
  </ul>
</div>

<p id="notice"><%= notice %></p>

<%= render 'read' %>